import { useState, useEffect, useCallback } from 'react';
import Head from 'next/head';
import CustomDropDown from '../components/custom-drop-down/custom-drop-down';
import PolarisTabs from '../components/polaris-tabs/polaris-tabs';
import { optionsArray } from '../components/custom-drop-down/options-data';
import { Button } from "@shopify/polaris";
import { getProductsArrayInRequiredFormat } from '../utils/home.utils';
import { filterProductsBasedOnTabsState } from '../components/polaris-tabs/polaris-tabs.utils';
import styles from '../styles/Home.module.scss';

function Home() {
	const [state,setState] = useState({
		productsArrayFromApi: [],
		selectedTabIndex: 0,
		filteredProductsArray: []
	});

	const getProducts = async () => {
		const response = await fetch("https://fakestoreapi.com/products");
		let products = await response.json();
		products = getProductsArrayInRequiredFormat(products);
		setState((prevState) => {
			return {...prevState, productsArrayFromApi: products, filteredProductsArray: [...products]}
		});
	}

	const handleTabChange = (selectedTabIndex) => {
		const filteredProductsArray = filterProductsBasedOnTabsState(selectedTabIndex,state.productsArrayFromApi);
		setState((prevState) => {
			return {...prevState, selectedTabIndex, filteredProductsArray}
		});
	}

	useEffect(() => {
		getProducts();
	}, []);
	

	useEffect(() => {
		console.log(state)
	});
	

	return (
		<div className={styles["home-container"]}>
			<Head>
				<title>Product Listing</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles["home-content-wrapper"]}>
				<div className={styles.header}>
					<h1 >Products</h1>
					<ul>
						<li>
							<button className={styles["export-import-btn"]}>
								Export
							</button>
						</li>
						<li>
							<button className={styles["export-import-btn"]}>
								Import								
							</button>
						</li>
						<li>
							<CustomDropDown 
								btnContent="More Options"
								optionsArray={optionsArray}
								onChange={(e) => console.log(e)}
							/>
						</li>
						<li>
							<Button primary>Add&nbsp;Product</Button>
						</li>
					</ul>
				</div>

				<div className='products-table-container'>
					<PolarisTabs 
						selectedTabIndex={state.selectedTabIndex}
						onSelect={handleTabChange}
						productsArray={state.filteredProductsArray}
					/>
				</div>
			</div>
			
		</div>
	)
}

export default Home;