import { useState } from 'react';
import Head from 'next/head';
import CustomDropDown from '../components/custom-drop-down/custom-drop-down';
import ProductsTable from '../components/products-table/products-table';
import { optionsArray } from '../components/custom-drop-down/options-data';
import { Button } from "@shopify/polaris";
import styles from '../styles/Home.module.scss';

function Home() {

	return (
		<div className={styles["home-container"]}>
			<Head>
				<title>Product Listing</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles["home-content-wrapper"]}>
				<div className={styles.header}>
					<h1 >Products</h1>
					<ul>
						<li>
							<button className={styles["export-import-btn"]}>
								Export
							</button>
						</li>
						<li>
							<button className={styles["export-import-btn"]}>
								Import								
							</button>
						</li>
						<li>
							<CustomDropDown 
								btnContent="More Options"
								optionsArray={optionsArray}
								onChange={(e) => console.log(e)}
							/>
						</li>
						<li>
							<Button primary>Add&nbsp;Product</Button>
						</li>
					</ul>
				</div>

				<div className='products-table-container'>
					<ProductsTable 
					
					/>
				</div>
			</div>
			
		</div>
	)
}

export default Home;